// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package grpc;

public interface EchoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.EchoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
